name: Scheduled Playwright Python Script

on:
  schedule:
    - cron: '45 0 * * *' # Runs every day at 2:45 AM Vienna time → adjust to UTC if needed

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install Python dependencies (Playwright)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright

      # Step 4: Install Playwright browsers
      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      # Step 5: Run your Python script
      - name: Run Calendly Script
        run: python calendly_submit.py
